name: ssh-deploy
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to namecheap and build
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cloudlinux-selector --interpreter nodejs --app-root ${{ secrets.FOLDER_NAME }} --json stop
            cd ./Eureka-website/
            git pull
            cd ../
            ${{ secrets.VIRTUAL_ENVIRONMENT_COMMAND }}
            npm run prod
            deactivate
            cloudlinux-selector --interpreter nodejs --app-root ${{ secrets.FOLDER_NAME }} --json start
            echo "Deployment successful!"
