name: ssh-deploy
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ secrets.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      
      - name: Generate project files
        run: |
          npm run install:all
          npm install @rollup/rollup-linux-x64-gnu
          npm run prod
          ls
          cp -a /frontend/dist/. /backend/frontend
          ls
      
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "backend/"
          TARGET: "/home/${{ secrets.SSH_USERNAME }}/${{ secrets.FOLDER_NAME}}/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          EXCLUDE: "/data/, .env"
          SCRIPT_BEFORE: |
            cloudlinux-selector --interpreter nodejs --app-root ${{ secrets.FOLDER_NAME }} --json stop
          SCRIPT_AFTER: |
            cloudlinux-selector --interpreter nodejs --app-root ${{ secrets.FOLDER_NAME }} --json start
